[StagingDefinition = [Kind = "FastCopy"]]
section Section1;
[DataDestinations = {[Definition = [Kind = "Reference", QueryName = "DTR_DTC_cluster_nettoyé_DataDestination", IsNewTarget = true], Settings = [Kind = "Automatic", TypeSettings = [Kind = "Table"]]]}]
shared DTR_DTC_cluster_nettoyé = let
  Source = Lakehouse.Contents(null),
  Navigation = Source{[workspaceId = "d65a8c5a-8ab9-47a8-94f6-18a93be16d6e"]}[Data],
  #"Navigation 1" = Navigation{[lakehouseId = "0229fa72-7799-4106-ab94-61fd29fedf56"]}[Data],
  #"Navigation 2" = #"Navigation 1"{[Id = "Files", ItemKind = "Folder"]}[Data],
  #"Navigation 3" = #"Navigation 2"{[Name = "Fichier_DTR-Perf_DCT-Perf_Net-ADDS par cluster"]}[Content],
  #"Colonne personnalisée ajoutée" = Table.AddColumn(#"Navigation 3", "Personnalisé", each Excel.Workbook([Content], null, true)),
  #"Personnalisé développé" = Table.ExpandTableColumn(#"Colonne personnalisée ajoutée", "Personnalisé", {"Name", "Data", "Item", "Kind", "Hidden"}, {"Name.1", "Data", "Item", "Kind", "Hidden"}),
  #"Data développé" = Table.ExpandTableColumn(#"Personnalisé développé", "Data", {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40", "Column41", "Column42", "Column43", "Column44", "Column45", "Column46", "Column47", "Column48", "Column49", "Column50", "Column51", "Column52", "Column53", "Column54", "Column55", "Column56", "Column57", "Column58", "Column59", "Column60", "Column61", "Column62", "Column63"}, {"Column1", "Column2", "Column3", "Column4", "Column5", "Column6", "Column7", "Column8", "Column9", "Column10", "Column11", "Column12", "Column13", "Column14", "Column15", "Column16", "Column17", "Column18", "Column19", "Column20", "Column21", "Column22", "Column23", "Column24", "Column25", "Column26", "Column27", "Column28", "Column29", "Column30", "Column31", "Column32", "Column33", "Column34", "Column35", "Column36", "Column37", "Column38", "Column39", "Column40", "Column41", "Column42", "Column43", "Column44", "Column45", "Column46", "Column47", "Column48", "Column49", "Column50", "Column51", "Column52", "Column53", "Column54", "Column55", "Column56", "Column57", "Column58", "Column59", "Column60", "Column61", "Column62", "Column63"}),
  #"En-têtes promus" = Table.PromoteHeaders(#"Data développé", [PromoteAllScalars = true]),
  #"Type de colonne changé" = Table.TransformColumnTypes(#"En-têtes promus", {{"UEsDBBQAAAAIAC9WMltUx3oyxwAAACcBAAAPABwAeGwvd29ya2Jvb2sueG1sIKIYACigFAAAAAAAAAAAAAAAAAAAAAAAAAAAAI2PQU7DMBBFr2LNnjpFbQlRkm5gwZYbOPaksRp7rBmX5m4sOFKvUFMQ3bL7/8/o6/3L51e7X8KsPpDFU+xgvapAYbTkfDx0cMrjQw37vl2aM/FxIDqq8h+lWTqYck6N1mInDEZWlDCW20gcTC6WD1oSo3EyIeYw68eq2ulgfITvvlsqf0pFE7CD1yURZ1C37M0VIFDc+CLea7t7tuttvRmc2wxPCL8k/B8SGkdv8YXsKWDMPyiMs8lltUw+CSjdt/qOpe+L+ytQSwMECgAAAAAAL1YyW0Mgh4goAQAAKAEAAAsAHABfcmVscy8ucmVscyCiGAAooBQAAAAAAAAAAAAAAAAAAAAAAAAAAADvu788P3htbCB2ZXJzaW9uPSIxLjAiIGVuY29kaW5nPSJ1dGYtOCI/PjxSZWxhdGlvbnNoaXBzIHhtbG5zPSJodHRwOi8vc2NoZW1hcy5vcGVueG1sZm9ybWF0cy5vcmcvcGFja2FnZS8yMDA2L3JlbGF0aW9uc2hpcHMiPjxSZWxhdGlvbnNoaXAgVHlwZT0iaHR0cDovL3NjaGVtYXMub3BlbnhtbGZvcm1hdHMub3JnL29mZmljZURvY3VtZW50LzIwMDYvcmVsYXRpb25zaGlwcy9vZmZpY2VEb2N1bWVudCIgVGFyZ2V0PSIveGwvd29ya2Jvb2sueG1sIiBJZD0iUjM1OWQzMjNiYWMwNjQ1MTEiIC8+PC9SZWxhdGlvbnNoaXBzPlBLAwQUAAAACAAvVjJbL93OfIQuAAAKFgEAGAAcAHhsL3dvcmtzaGVldHMvc2hlZXQxLnhtbCCiGAAooBQAAAAAAAAAAAAAAAAAAAAAAAAAAADdfdtyJMeR5bvM9A+wfpJsB8m4hwdN1Fh3k0Pj7jQ5JlIrm32RgSRIthENcAC0LvNr87CftL+w5wSqgKiu9IzMrCpOU9QMyG5kZXlE+OW4h1/+33/939/989/eXJ395fL27vXN9UfP7GCenV1ef3Pz7evr7z969vb+u3N59s+//93fPvzrze2Pdz9cXt6f4QPXdx/+7aNnP9zf//ThBx/cffPD5ZuLu+Hmp8tr/O67m9s3F/f44+33H9z9dHt58W392JurD5wx6YM3F6+vn/GF9W8/vri/4B9ub/7Kf31zdvfRM/fs7P6jZ6+vr15fX355f1sffn3Hn/e//z8315dn52f81+8+4F/wJ3+Jf32z5A1fXd7evr6/uf37Ya95efX27v7yduVL/vXm7OOLtRQ8fPjs3y5vvzvgDTcfr//wpxc/HfCCT/73xwesvn76sO+++ZgrWPmGj7/6wwHU10+vpn7z6YOof3kQ9S8PZb36igM24OWBGzCs5/o/fXWAyODDB0rsn27+dJjE/uXu7F/XvoJys3799dOryeenSf/6N1Bu1lNfP33Qdx9K/cuDqH95KPPVVxxE/oEbcPH6Ckrniy8PYCB8+gAK/vDp8/WfPEDfbT59gL7jGw5a90FqA5rn1SFa89XBWpNv2Ci/F2+/PeA9N68O175rX0EGXr+P9dOryd9q30Popw5cT3/99Gr6t/r3UPr/7ebuQCqef395fX/QO14etIsvDxWn+oqDyD/8IF5iAdcHUvGHy+9eX10d5yWHrghE3EAzXX97dXkAQa9ebd9Beta/h/r+sE+re/HBo6/fuvxp4nUvIS63l2efffbZBD154gVf3dxfXE18Njw7++DxD7Z+9C+/tyZFCTEMxkaRUJzwQ39556OyfXqwwcck1omT4kNKY0+XzdNmcJJjCqW4krwvdvzxLSnOiwnJDsa4ZF0KEkefNu0ytoSd2/E3r17xadewJSUFF1M0Q7T4twE1U5tvhlJCdIKHQ7TZdOg2BceUJJlkAz6RpUySElLOqQySBN9ijPXKhq5yNdft/Txue2QBLJm7E8TnEJLPYqaXfB4LdkUGh6PNJYfcZzdrT8VvT28+zTIWcdwjMUtZzlhwfPYmGS8hmCDja90KS/ApDwL58uKK91khvd1UN30AfvNrvMz0aMV2JVtMePiZ4qRg29HXNRtFic/4J4RsRbz3dnLt08K4jGXmycnj096LNRFcFl3OxaQeC+DhkiyONrnsJKRx0s0j7c7aHAbwrTXYB+X1i8TKHEOPz1vGzipibxWN0LosNuRQBMbCeLD0NDXJZHHO2OICBCwpJ3xCqW1Zt0jVHQI5zJDdouj+raXIkooMxZrsE63ipHYygxdxwcZiYig2pzh+xg05Emg5HcQoQopscJPk4OUlDXjMQwRhucafbtkZ9jBkEFMgNCZN60uszxmHLUpQVibm3tvnqpUwrldOBBunXvDvz7/44+cff3L2+f/64vmL559/OvGaeAD63G5RiBIhW4O33gWBrhzd0QZwJti3gk9AtcVSRk+rEfIoCRwGVQiriXOehF9QBCJlcA5cEI1PilgdCjjnrfi0a9g8nV0sVGuR9jHgv0eV4NPmQ/kF4yADYGPowdF3NybV5QICKga20DxmkhZbMggexGWKVfRRs/4HIc5lmz+P3aSR9kLzgBOgpgpJU25bYqyXBMVZiikRaiiMa+aDIee8Re9orVOsYxHTNWhmIdf5GHPwpRQhA8IMT2PO4uHmJCygeBhTzc1ZDjlttKMPtJAz++Yf7OI0BukaSiCaAgwByXfwFHz0k5Zy8ssWssw8QXlUUkA4eDdcUA/La8YVWmOhreQEpkm0nxqUegScQRKOf4gxhgzcA/x7IsC5WI/PWka7itBdRQurDBBbMvgWz0NIHeZLEKgM4YBzbw3F/GcX2faEsX/GgG8T5BHfNM23voBnBrAb+AiMnia1TQWcwUMhOOtBS8Dm9KiJBkgzQAFic1wnZMN3+oG7YzpnVJcJKQ/QMwIl5aYtucB6GzvAicTH6J/0xX+eOgnj+uT9hpph4jWf/3hz8fXF9ffKxx9WC5/NCffT4QyS80pAKz4pNKimAoMAixaSFv9KT2FBgyfhOAmECd7Evup9eDAmQCLwixSTQ/Rwukffm3cUTtS10wfLl3gCmjfPQVHROYILm8RQN3a22EjOJkeIDrRRUgTtiVzj4Z0FA6+xuOwL/jROh82U3MHnhNOrDvveixdjyFU7PJOJ4pOqgg7MOToDNUX15r1T1ngO5erLYGB2rC0Wez3uV+4y0oS3soKR5DR0L2ImWc9M2boEjUkHBZ8Yp8LBb8kCM0xoZUmIsnH17UXfXvzaPYbErBLBTa0uhyeHB1MI3Fq/b3GnQFzrkUTudbQO4LbkfTO/QWTjf72QEfr8vnlt4AsrZISI+pTGLbI0hpNmViIk2rrg9plrw+sb7OScExlCdin4HJRY2mzJ2Hl4pabtLqChvPQob+TOluQZm0zACCV4Ow67n+iIgJXOG0f4gQXs+0anFL7mPLPNQMAm8F7DSFIMimT8HtsRMpwpZ7AnilIBxoM4J2NsjJZRXZlmVGK8ACkEMEy83Ur7mHCzMhN8tEPET+GhKNHEdmUhWMcouvMlZUVqc4aezEOBrwpZASU9cmfog6pixn27Xy60e/7Xi8s/f3J3p2W9b8QmZlfgTzK2nUTMPjB4B3g4iGKpPB6Bf/I4bk+teYOmAisyQACDgR97H9maN3ptwN5JwN4AK/6I+G7mMk9E98ZQGFJB8YFHJYBg4wYoPnIudjc5mAMPfyb0zJ51EWIDCix0ToLYK0RkakkrcJJ5sxFHHKmVAG/hFs/kpKfdMFFgjgF6+Gy1HQruiIb6IfsQeDmnuLirwN3MJcrxaV7EQbKSg+CQw9XPYmOCB7xvQTdEYDVuCIBE4CFmOhwH141bhwbWweI2/zP7N9ybrewdiQPYBpCOORcBjNIERbGXC1mgz+UbqybFpUHERcAMmCo7Lg3NMgCdPHxPsRlgMWhxoi2uA7Dwde0O9jiJktlwCK5bKP5zVvBEuu2S3gA7hsIS3gw8Ae8b7m6HkARgAPATiwVoGotxnU74GvADksUlLDNRLSvgJ8E9h61xgRsGlvKKjGK/sgtgpcC7aGihnlR4YFBiYVgv7sI++22EIsLpGBwzaiA6XVHLWA2I5BU03ZZ9W7N5qwOoBT/gAJxnzlTvvV1VsAPodsn8BQO6H2+ub/CL7y+m7TCgsRNsPrSOtfC+e9G6AAcgJMa9eUhl3F42ZgKnmsEmeNTQM1YUmnPgVF67OvzII1GCA8DcvBUen+TN11uG8gf4gomJViNQ6x3kAsc1wXMVmPfooWymDfF5vYeDfa33vpBKb/evELf7BJctDnBHCyQ3F7uvD1ajuWV7PJOLYqPvLFOm8oNxNPsy//Bg9NCdVI6wKlR5xwRz81YoRyd5ERfJAVwEOAF7QqVewCga25/7AlwCC+BgkWPMY7mDKwCdEmhq6QNJTjEJ59O2pfpnGQYW7wCwhmgzyUkTEuUAlp1/n8M3z8E2+jw4Gyyzy3yXq0KpcMUJlBPU0/ixbnEcQIJNA+2/9QZQQX38ACC3WLv2VvBEeu6T3gI5D2mDKwKQSKy4D4reIaTYkpksluiYYO8P099LJa/F5gG4D66UwCUHGs4KkzugM8ebpOy8Y2xR2bnzMAQHnAwDZiwAWOrEFKsFwbcaQkBnDaP0mpiVUAYBo8YI39OYbjCtmASwhlcz71OcFqXDL5yDhLuY4cykkTuNPYpHtcEOkDv/h0Fyf7+5m7S+LrPIgPncwqTWtK/b3sVwvI5MIUNI4PEoKbY7CKOEwCiRA3/Aou1HUbcqA/ouDJRusEcO2sX7Khw3c5WnIXsrgsCFhtHkeu2SlPSJBssVQ+8c2tEDLZbOXRmvGSwwA6yv5Ey1p0YRvSugGAqGGQvWjeX7r4RyC7d5JjO1N694v8frqcZCLqpXeg58atLApBZPK2kVSlbBuZmrlJOQvYiZZCUzMZwYi4etBUuBQ+jKKBiEVgcIyTtDvJpGYibLEZ0SYWqoc8GX5kdQjE43bAAzF4SJCtnWBHZtlZrpWcQIfXZ/eK6WdwzRAVlUI9iHL/AhjYvUP8AC2etpBlvrlmwJDM1HsJgvXmGHQ7DdCo3bXURDve9TvwPv6pshNUDywDQ97g8sS4DEBFCjMsWJZLC9N7Y+ZstahsRLTc0CMUDG/DnDFAnefypo9NwNLG/IhFUgvXilZGQHKknhWdARxaes5oqcl1QDgSYZi5/QF9ORNS4OEBeuFBkE6tGrRAM7g4+gZiwINwDS/bB7Tzm8nzG7V5+9evHFq+efT7zmGKUcyWQYIbACONsrYtmkitBbsDBeIfLGsVOtFUzNDYVjCvThx5NbH3MycwRktwOvdVh2o2RFHFrHMWe5J13A9q4f7lTIYYCRFHxHGVfRTdWwwEvLUHIOno1XRLVJW05Unz7h3T4yIjRJueNuwGwHKNKEUz1JEceSnZ/HaK1iKrDbsCwOK4AmcUpuxvYD9GRzHLCXIoXZyEdIN1/LbTtFwydZxiKWawsQl/AcqYf1jXDpAf/A/kWLQD2iDheNgbxEGGAGcrSKxTVlHDIesmmJNSZ6ekUBVtg43n1PZnYr3/i4W1OfnfzlIh6ZJxiPr2Ymlh8cU/Y88zz7RaSJTqCnnQ8MZE1XbTByA8jDfH6wqqI2Dq/ZWKazZ66hXYLtLKGtEI68r4z0qyPzZzu9M/AgMEcEewHVlKyUA5xUQNvjhTHLjLWZ4srINcLuxgDq+cHTksAMTpc9MJePrgnAaRSicN9nNVgaZqeAcEsEOs3JgfkhgzA5LwncAaXLQLvUVKvoLeuzAZun63aKSwbWHp6fZOxlp1JmifYI4/z+fuPKqQjiq9dvvr55c3GtfPxhtQ7g3HuBo5Xg7EF6p2+CWetuuZm28BYoGEVmmyIIaD/GrWuLimS0IogANs8gg4VB0TijBNzXxRDnrfEEND88x6Iu6Ate2ZZSGOXr7XEOrPFLcE0jvPGOB05zHmlsjIG0wVEdUV4btWVqkMp7S1kIbqSiam38cOkWz2OjJoBooSWsZ5cCXryLVpxyHgIvSoZ6NNgVLXd8Xfxw3irlFFQvYiVZyUo1cMDrIx5O9Y78fi3FlmSfbcY5OuZ42yLlGDl+ufSvrI1lFePjP1kNl/fu7CAvMSVneG0Hs5mjFsrQgpTL2GEG028JFxzvwCos1ge43E3NMnAuYEPFBiAYn0UxotswIuyhSyzggpUGy4ny/oOiiEsVQn8JT7TnPu2NDHqKlgDoRIuTLqEXo8aeQ14Kb6FZ3aZdX55IFJtDlZJZlAFEzdILJYDniVZBBdQ+r7+9kvJqBnHW09cjBdjhTtLBQ18sACyBzwemhb3Yv+TfPOoisTDkJ4oj7lOKLpt8BuA8CEEJjhmIQUv5w9ICOSgzTsoLjS7FfdWwE0H8h4F6n9zd3dz9+fMfb67eXN7dXV5/f2YnzTVkjXekA0ulWFc0Hmlt7o6ZhZtsdIGFz0p0rTHuyfrM5kCGVYhBy/ZgbDrGQdg0yeMDR0z/m7nA45O81X7CBO0BzB2EwZNe4QJeChgZAeAM1U4vvxKaz9Fw0UQbtsBS8B49KluTnaFvHLzVY+G9hfs7j4Ha62I4vRaOdcAu4/+8VhRxTkKw0dB9gE65aG3gVsG9mYuUk5C9iJFkHSORYuAQeNI+McPd875KpZiJQvC8A3N1soxkOC2He6EPC8DkrA72jLU6gUVQrNCMZECGzBMBBkBD2S813jypyNJCZuhy/GYDePHHoJbkUrOKeyACaMOZwgtRBp2dVvO+RXoR9hgKgPWVzAosSnO3Q5DeYlXbX8IT7a5Pe3PEYJFYgDxdKrWqqndb7CGEOJ8A1c/iei254zRC2FaAZcs8yox/ubjfVmSzz0CjofYdNY59v4LCUrwEL7ZYgE1hhQcQbO/74aQGfDf71EQnQavsAG0Shpq0mpyIlofaLgyMwX45FjjaMQKq2SkCaRsNbyIgNJ36nVlaYQfo/ZKuipfhPDdpph08nuDLgxC5sfSld3CeJSS3/FiUoIWpm0BZTuxtAoMXgEKslkIako/Md8629gkqs2Iys4N7s5Z4ApofnoNvyQZSQxB2EAYmm4Z6tXeTSYVODU2v0jy20ZbCPljJ1RomG6OaTQtpcFAPESfHXP54vNzAZTs8k4l2urJIhCOfTclMr8n7pG85QdgIDwqVfRlc0TZvZWxv1irlJGQvYiVZx0qVYpYDFrbH8o7p5/v9+DbPpmyAYGBjEkNWrDI6AtpL+8GJfQq9deyEFGBrJnDTnNqPtW9axQ99rt+8NoFPLNxNtgqGke5WiNbeAsATybDo0ind/B57s/hsec8L3JEz2EnphHNYZG+pwu2toCHddknf6c4CbGEsbzIytKOCGna6RfGATAHYxlf8rFLYIvhEcOjAlRDEpLUMsjaWzLiEY4auHuRmcUjMyScALMc2Kr2wInbBQxEJi4mpBjTPhMhtYCZzYbBuRsWtI4YGlIzwfMEkGppmT4A81L467EPr98N/y0V5N6p3NLQ3gdKOPhkEOx1sTolehjDTdLIXLl1GpiNbBl2tuPHWCE12Q2LjD5bG2zQSBWrosJajN4JjB0sDRlWw2qHZffOWe8IFPCpMJk1A0EIUyK4fd9YaYQfTZvgoeHgkhLBLM+QRdhQsSzmDNzbdtpd3UHCvCtAmlmq1/qWHpfYt2/Z5XLaTdQzbYF201gfWH0xORjgPWHPtbB8y1Ww8RlrSel7bSRo5xToWcVzb7HUByxnrmGTPUkQOGBDFRd9Gh+BVFE5dSEmY5KPN0FiR1weL1Z1eYgCBLC+MvIfJtWo262bfJrfpoRkTM+mLYy2ohOkut0qUah3HzJOTxyQ5y17sAFDimRY20vDnnZXZ2hhICnMEjZK99JjoB7gQ2QuFzVwsCxYOl6nRVL+lCnzOInbW4HpraHP9HO9WjS3MWpCRItl3jIkk4r/KfLAV083Xjy+uO8M3wAHeecYXXGK4eJItA/bC5QGbWPu2TI/qOLcDQF4RtqcEOmbcu8dogFmBvaiMcFyNgny3bAzcbfyQeFUOlo+djeFaWW8jBQYRCpNl8lOvd+Lx2jB4Kwl6LCu9v+xyfRJGFcppYOKsQuFPv/jjl19+MfGWY1SPREaErWc2BG8D43jvpcad9byOgAEsMbCnRQfqMEqQgFpStNPCbXFKUu8khGWHToH/h+LLecs94QIen67d0mSAtoGWHNdMbfGIT4GlZoAfbODUMaGJjehdsSYZqKiRTIodgQ0JZ8oOcjWBOoliAg9DmMs2fh6f7SSlcEYLPGNYeXjx0yMdzpmiBkxteBPH+4eRoOhREOa8Re8OnTvBOpbw3E5y+iKmw1M+OFeAMYMxoUxPaIxwa2qPWXBnZnfeo0FMDqyaIvUhIQh2iZ3YYHhCDiN9nXb3uXtszCZnpCUVT9eSzSumbfAk0FnGNvOE5amkhD3igDJrXhi4pl9SEnk/XjjIEqpNgaWPQNOCZzKQFysOEguATwQ0l2ryectoVyHdVbRQk9xUGMiEix5DN24RHC8/OaIQatp1hqudQHB3DhiIvU6vZOIkeGi6xiVQRw1i2eMfGHJ6Zh5rtS2ejTEzk5NFID1qgNmL43gPxk+t1jJnC30z5whBCzrOAukPncOpRiL8mFhhNj0b0gBUM9Hg4QI6zCj+m6lWwrheeZ+hZmcQyNV3N2+vbt4qL9hwcYZ/l5l3W1gwqJ1Wk/zG1rcmi4F2Y4vNXnohIFdi53RoYBGx+w2JNizjmR03MNYe6UaOvnVlduGsFR6d4oenOAMiULPjWRhVzQtsLvWdg1uUHKUHnl13OEKxYGoWF7PRZwnavWbNFfEDuyaawImyR2sTvXh/53HQTjWJZz9lFpPhK9RrUE8KwuDEcl5RzMrcrZXZhbMWKScgehEfyWo+8gUWxNU7ZM4e1hLrAAsz2AiMxpywkRYyK26aOzrkQYdzwLgwegFzwVbVyn72y0jwpuJDcBz6BXyi9T/RbvqWMcIMbt8QDqRqeaHARqU4jKT0Fmg6/ALVJrEcEM0ZM2ou7YZ/WBnnBmalsTZU685+WG7hQkXQXUFDuu+S3soeoJvJxDeW17FKDezTXbNx7AjF6WzF0dP7OUWwSR5gz0V2w+Gw5OK0HrG5FiMNloXqnk1l9ZbRAMmuzsgoaUYJi2W7xwzXA5JBpK2oLGHuIZAmlgXfSqsBa5blLTPgS63T1hKzEifS8QZ7O7Ct34yprxKqljl++ch/K6z78ma6WbStUyto6Av2XJQ4b5PgFmuKkY2louNur2i2omCtLcsuOH1M4b2ANya2gCyJ2epK9Hgdnpu1whOQ/PCc42TXKAPnQGRvg4IyGsDsebnHxkps/SydVo51xATcGp5GTZNRkSW7F7s4FN7mZDg1I7kkaxHdoh2eyUNtCiE8PZjfWEcUca2aMS9seTJwjFHhvcLIaIcDEN2sRcpJqF7ESbKek2xm7R51dGYu4X7O1cOTtTgS1hgrYzPCONIgY0W1iFJYuIPqAps9pEwjBhtVNFM2J4HQMZNEXG2zbhj1mwsQ17BDn+c3Zo0D5wZyTRLOu+82rzOFM79h270nl0UlDrhFdTR8OQ5SCweslk52EKhbqG37C2goTz3KmxMGLMIhs92/B0wbqbB9hxBwvGPJeAFX4YjUFp+nEcK2XqMQhCW292Q6nCaEsD+e0wrgLFj2blHVC+e7cYoANAtrXELujyIBAMUqnRQ2k9D6LNY5UgK9luGCWC0Bql1YbUfFiXWJt2zaVEbLnM+A89v8MyODsKsWdpHdz5FCeHpk9+rri6urCz9pmT08Q4tjYjN6Xrl3mpNA9Uiwkf4Czsdp7X2a0BdAEnSnoR7l8FJtJCKcCagdU3IGP+exYNJqeDdziSegeWu3PNuSDg6aLFrfKbZmY1J+PaBB7VYwlnu/F2iBQqqTEdmULmkF9ZbTSwrTEguvgscGaq8d3Ltsh2cyUdyFHZm3WFARVh2QzCGW0P8+U/MkLZC/bmbvvBXK0UlewkKynoU4hYRj3DmYi+1utU4oRH6sQSxSUtw3KGt6Ris9vB6JG6dkvFPfO80gbIlPP9Q2vFrbpmVH3mfqzRbCszJ+YEVE8FrnuHeGHrDtgLNUSTCMnRbRgQNFhlAvpkyM8QQtoheK+6xFNNS7PvU77V0cxyDxmlWYydqrWWTzKwaw2NslycjYs1NKXBs1jjawYNqxex/dJQ1FsZhi8AL9wEkhVos2nLvBsr6LJS7MWYydQR0MasIEZM73dMByopfEA017wOXMuSaeo3RmdHLGfhhmiGJ1KWtvZv/tMMi2xUuv+fSozD+Ctt3f/vdhthfPv/zqiy8nXnKMdD4bnLHWpZrLmoJSUtt0I8h1jLXnEBfOvRh7ukn7Z05v8JFTAeG/TFZQZI7zSR4ohNX/4ubkWK1I6Ju34JMuYftuB3kB8hsgPMJu85M5fTVmz9svXkhkL+Oy85QwAkeQ0sg0Zs8ZJlOUwFEH9HS8nGB2dVDuuA/M6Fu683NYrdWDUnsVMGMjM0dmvyDunc0PuTaFMtEz0/5E/aDnLXon/fgU61jEcju9h+fzXO0H7Wr71VDSw/Cy6R6yTlgaPIivgZlstEzuFUl9Tkli3akbqeNKODyPbZVtpyFtNw+Jl9SCncoxlDr9fTpHazrddxnbzBOWxxwo8akwNpesIa3jLY2bpfnaFBQMkzk8QvOHtkAcuhKICN4Ic1LrtLzDRWs0o2+ZQpm7jJ1V5N4qdlJxYSQMW/gZ4NIo4+f/RE7KHMPBOaEcIDzSMenkkrtTVEFEVl2KDCwZtKTuzes5O5gjR5i0BjvTSV6FRQwxsFoZGq34btod0xdBDNssYhkuTBeQcOp1ZIJhKA7cn+YUywBek/EDk0Y03+DJrwR0H6Kvn4il0yp6gWIJo5rlPQacUzHCFxd3951Jc5bdfmoFFABJZjeU0W1pe0RH1k1yEJvn8U7fKln4TtGxEAteVlQ7kNFbg5M3sAC4ljPNSTeZewE8b4VHp3jDR47zvO3A6d6BpZi9FjLsV1vHxUOAODN+klhTM1uFsXroWjqdWhaGwLpAHjkVHXhgbPLa2tvfZds7l4Ga+KBnuV3msMnEDlpaqCfmwmtJCLbFWvMxe0PPXKMcn+ZFTCRrmYhtOVyqHWF8HOlIvOUhsM/AbrvwTGqdq7JpSyKE2lCcnXvfHDz4JDif64j4/aqUzbOd0MX4p5S/XnzmXb7eEJkTCx5YKMvIMK8jOi8GczDND5YxYfOL0grlsSugY5+5AfwHq0scc2Ba60iIcLHId1fQkB66pO+2OzEAOhIKvRal7XGTeQIdGIg0oLzTSDbqKaWtobqOqCqObb8gRlpXZ+8lsBu2Zct4ybJfeL45M+xYnW8PShlqy0rBQkMAkCL3DY4J6xz3iz8eHmQzFjox4i3+H7C+uzBsG3A5wJXxkGu1m2dJYuNQPJMnjVYqLIsUwE6w8L254T0IvL26ub4/+5fLry8nzS+gh3FhYE91BrqccufwZE5zYcYwWByywOEyvawgy1FSHlgIIsZ8TzUhxrNRKCxdziEUHPHxENzMNZ6A5s1z8ExidgPUV6Dx6xZlsAEURTYn9o9XYg7NlbRhvbFL8NkiZyVprUrhRQkc68L6sdrE5FgYbvEGz2OinZ7PluMvWO3PcZv6fV1mj3fGbSjlCRbmiFUZM5cpJyF7ESvJWlYy4GKYIwaTKkLTpl5YaNIgQ2D1aKQ/cIyOzzARPfKs4TSdaF0EmWOtBzdv6lgaQ4DAKVqw1WKCWgugnMJCRpjB79v9kQQIPUjIKRkOc+0txDlJznpeoMbqok1iO5watMPAeRTMs/NKs+JDsN1iVdBdQUN66ZK+c4GZeAftCRpL1IYwNp5wZJNl4BnOdxrpVH1KAWwwkMuc7QIiIhBm0UAb+1gLwJ0B60Yylpq/MOC3VjjezNX2AF0C2HqArSoBnwvOUCvwY79ENnFmNxjGXnuvxQc4q1lYqBZGGgNs1hUsZ5iy/zeLvmKX3L5G2IF2/xDI7vMfb978eHE9XZmRPOfSczp59GyvqYSimzEeHGfGgS4OFqtvKYJPOeeaj8kihv3Y9ea9hf0pwkP+C+d/HzF3b+YST0Dzw3MByhQiOjCszTxWJWTUTvLgmC/wKPQcN7s/sVyEE3xc8Eyq1Xqv2wi+T3EgdOCYt5FY/Epgt3CHZzJRi+s8PLhYIncy13x6RY85x571Q0jUZoZxsePhupmrlJOQvYiVZCUrkWQ446kOIzSmODH7I9k2j3IuvLFDYXAkejgWx2jvbLUDa6d5AO/Uy3HDCQYcnzpO4YyMbjAg/P3ISIzNbFimHc/43y9kiD7bb55L3rMDc4IZToUGvA8GkqttkTmix6s5qxvoBQPvA5EJEcesiUnLsN1ifdulvyE8dghvzjcyM44AJVaG6U4i4A1xsKzPNYHlrlpW32lksK22sZytHaKA01kcodDBmmycozcggs2Y9dKMwBqkwkwmT3bv5h0z/bBIgogHKK+oVYdnL2IGoGzme1jOpeuvLLHyNwRfCosD1ZgkO2cPNSEdvCpK81RZohR28N3uEfxC8d2L29f/8fby/vb15dn52ae3F9ffnr26vLubxntkK1ZKs8ad1dLdi0I4+REgSNLDffy0EOU6cZBdb8lpKapjbzMwk2WKMcyNUEccD+7NXOHxSd7wrgS2HB1CDdaXXiWuHWyCE8N6zNoNrHO5EGqDTTyW4fuz/ZJCLePuUJODhwkHOLUjOR0rsd7C7Z3JQM09LNS8cSwkgL+GDdfG6LHZsCsDYLopzJlTJjWtQnoz1ygnIHoRE8k6JiL2CTlwChXTlUzSyDiHi5+ASzmwzTJ4fYyrWOmE7x669cOo+ADu5YAIzvDUUGjvYKxLAWwHy2cTe2lovpFyPbuQE/rc/vAc7LvY6OBpBuJOLbHoaR2wxZ5pIrn4Orhe60S1eT1T4ySxPJZzM5LSGvIQkLdQDcxYQUt67pH+tDNswMLMB4BlKD2j9Op7ooMd8tlHi/33Clv9/pwS2JY3YNs42jvXXsZeMzuWnrqlREAaglP7qpwzGpbgz9jA+yjT7QBksDyO2/Cc1s30P+VAOKpRgKUF62OpmdLDrxU5dsOxLhjmCVq1uQp0Cst0mFhHTorKVZ4sUgu7F7TvS8+8T7764o8fT73kKOUcniFcpsSCv+EfjRvEtjtzkcgW//lhgOjY001z4xILMH4ELnccNDiZN+ng6IjJQ+FIepGR6vL69MH1HLNWfNo1bEkp8GAhowM9G0nKxLI2i4fxRZdqTgeHi09TbgTwIj10mucFspKysiWmNmDn/RBwCfM1TjIHZNnuz+O3nZrFzCaGuQ7DsKnTqfbcMUfX116pCUotKEGHw4s6Zq16dxDIKRayiO/afq8LGc9RlTMXhqOts8pKW1BQW88SKgLVaMNqVpR0eL9/wfQOoTA7lvnrPkYYYqdYk1H/f3+XAM9zkqefmj3fkjdd7rGMZeZJylMtSRHgTHyGbfyCVnnS9rV1wptRRm3ZoWD87U8BWRtKiUNtZQaVeAyxGi/oWKjL5y1jZxWpt4pGaNmKEToXetezWeZ4onjTotmlGicD4Ql8fwxbsVRmd4oceBUknD0kbDk4LQucLw1+GyC5BOjarOGnvQHx8B0pbdgbURz6dvRMpPHK7HYjSeuWtY1vWM5HHoilHzpZd2vmsjEmxdr0iIWMI9cQ7VqtNaycJ0jm2Hul8bxdqlbCqF55jwHn5ITg+5u3375WPrw5Jmw1/KKB7SnY6ESBUm25QXKMfXsOhSlKXWN7A1tYvSQcPcOqeLU7HnQeSyADXpyZnTv63lVhxJlLPAHND88ltmgqAvgg8LFjUsxAc2scSsL3JuaSsSN999YlRWgiQ/ePJacaHZJ4LTP42g81spnN3ntXRhIX7vBMJmpvjWFFjKuzMh3nrOzHBrac4NmLaxC2AoXhtWp/sxWxxJmrlJOQvYiVZDUrGebqML00MsXVGu3CiFmOjlvByNhIztCaG+Pu8NhxUqZ7v9RuNtj4HBPxFW/x1USv8b9feOx95t4ul12X3MA7gDqstdtljYU2vHSDrStjubxt3DARwtQhDzkGJf39oKjhYqXaI7+h23bobrv2eZ8K7yLZ/w6OSq+ZV/XdGHOyifPhtG72J5Kz9v60AEaB7siFhpEpUxsYwvm5cQiZXJK1rulM+sts1mQifLvo+0FLy3H30EuO/V+xh2oXRexrGPDlpkCTST87D0frYygcxwOvR00nhmtgCge5JpYqd5l/VHG8b61eDoNqb3r5fZ4NIYMb2A6EbRG7RQWeExtsAdqNMP2d+17G1Apv9fkpTqrdP5INigBugIQW4h2OU1HK8db15pu3xBPQvOFK4RTONBD4wW0ZQVLvIjVWcbFbQwkcezGj9zJNawy25tvCvdQqyiBDTgYOa4oPfYGPBdUWbvFMLmqb8/lUR5lbXhzgI9qdQck5D2w2BY/YAm0csfp25hrlBEQv4iNZz0eGc11rdAkueSSbKArceW/YdRUksyhupEvCcqSmXXLupPYBcVkWjxvPDm9qdkP3ZBiDMQamiv+V9ntUbNapt55ewgp9dt8olGQkOrbsZomhNt54JxveMHrMYba2JsdNojc2yQ2sJAgguI4GPDp+W6xquytoSHdd0tuyDU8MwEmwga3vlAyxxjt3rBpJEBReKpt9jj6pDLbXroDAhVUTUAhGZcDC29MhO8vAu15aeF6LjaPNwuwk77VmX818FpvZ7TBi29iUcB9yblg6xVjyIAULY/+9Dqamjcox83bKCp2lkfHMGxvl2Jd8EBdrt5w80v/znRf3lcIOrvvF3Pl2Sjf+8+biz19cXb7pFOZyZhZOc2DXuQSvoDO3CgwLC8SsyjoUORilfU9beAXkAQRkieZ5pT9+rniVg5VL0UAcyAJHBHgz13gCmh+e48hRuFHwOygN2LfutDT4PXUIDRO+pVutCKZmBKcwEMchPlozWceGMbzVhWclIxckK8Hd4u2dx0I7gTgoEWtqH4rkmcWtqDPgI8vblBzqrRvgyvHw3cxlyknIXsRIspaROP4j107F2aW034F/sxFQ/V6GkG0qjHAdpcFK6c7V4jAMA5+EFzVSYFm1YRhd3M1KXAgKZ8ZnM9K+Y2PKlbcvY4MZ3L7ZHweLbsIgQNUcMzEjaZ2tRMA4Fj94ydgZquFCspGsUxKRxn5hzsHobrEi6K6gIT11Sd9pyOwfAsoQQHgh3TmBnpcv4Hn2lByB1SeUvhbZJV4TJhaaximAyQJliew7Ayo0F8cMnLiR2KSGHW3yWOn8u8G5yPYp+AiEY6wB7WZZoE+Ih1keA2jZR3YZOJEUWNYZc2y3Yp6EU40ZWy0JCFMJNcsSfbAD7N6XmtxDgd3V1zfX308aZDbzTC7hjDxrlo0SF26n3+aajwvNA52uNUVp5FaYQUncIczVTFoEjMfty8BehnCa2ADxeKBu5iJPQfSGn2pXIs8rhmjx30pI8mmX2ZgssAFSqYLZI9eyU5fJnk0aoEO0CSAstILVgDOdAf04wPFYuG7xDs9jo92yXJvwHRbqv4Q0UlG8eZSKJg9Mo4SHr/X6Xdkzb9Yi5QREL2IjWctGXkBsYMOtwFCKgj6gPy14nvXfgQ2JjlKN65UpmoeP1WD1X83ZcYmhauUAtFqNZUc+g6+3Bx6sY3m8ZZCBgcM+EpXAbH/rhDWeRR8FuKHcR8dZBQBMLllGo46O4Zar1f4anoiPfeKbc04shWA1ghThfX+PlMhkLjYaZS1pCfulHyeUuLbpT+YsNw/QCpBkR5qJb0TOJvFDjni5YfuHfYC42TdOpeVThE9Atd0CCssb5si2fIa3CtrINfw6Am4FYxmnd0bpfdyWnOCYOSQIao/FgZrcBeC3MFR3ByaXSY3TL55EbXOuWfPa6ocnKQljOaXBczif49gRFtLL+G1Rk4Jh2KPK82IZQHr86aeczyCR8gUnlGHf/ZZdLSUc42qs8QNzPHLWGjAdWhAxb8EnXcLmaQ6g5HjPga0wwXKpM+DCWGHnocyE2KxM+WuSf4VNTSmi7H80lpLWkALvrQ6zZ18NfIHmSB1YDbFs6+fx2k4oyhfeMbJoNHJHp6crWMObKIAXIBigBlGahR5cDTFv1TvVECdZyCKuazLtl7EdO6Kkh3GRNkMKtJjXlhq2c4G8sH2cLRw/2t/XmfUQTNPqF0TATBe645Tv0qmIUIhrM6FDYXO6kOipeE6ln1z85EEt5Jt54vI4iidENuEfck3dd1EZ59VkqCcmkLOvcoQd1SZIbVExO21nTtwLwlRHpRTr8IqIpcp83ip2FpE7i2iT/mu7N4dTFwuXZFz7NwURgFo4MV5UQEymOeUUQrszUYIFrrkkBiGdG2k6srProAJsA4c8ecb+FJT7eJ6woYFtuGMR/k+ZOdqW39RxoExohAoRpbx58zgvw03ta81r05j61RDCIU5M/oFjZYp2NbNdq+XkYvgKFs8GNoLu6oB5OiWMK5Ud9PfA8Y8wUDW+z3/66er15bdn372+ur+8vfvw17/67Pqbq7ff4q9+Y3979uXlT/e8JL09A8/Hs9+wnfEPvz37H80v7Nlv/uXt1dXHF/eXv/31r+oDZ6/vzv7n26u/1w/90zsv+aezm9uz52+/f3t3X//861/9++XFLT/CP41hge3C8O+7Hy4v7/FVF6T+zeXt95cvL6+u7nb+dHZ7+d1Hz164D1+6jeC/+yv/4Yus/Eo+fGHt+O+euw+fa797YfF1Vvs+iy+EI6b8Mn/4wmmvdQ6/VD75HN/5XP2ly1j/wyo/2N0q/PGvN7c/1q38/f8HUEsDBBQAAAAIAC9WMlvVgxIp2QAAAL0BAAAaABwAeGwvX3JlbHMvd29ya2Jvb2sueG1sLnJlbHMgohgAKKAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAtZE9bsMwDEavInCvaReK4hRRsnTpGuQCskz/ILYkiEqbnK1Dj9QrVEiHxkCHLp0IfiQfHsDP94/t/jJP4pUij95pqIoSBDnr29H1Gs6pe6hhv9seaDIpb/AwBhb5xLGGIaXwhMh2oNlw4QO5POl8nE3KbewxGHsyPeFjWSqM9wxYMsXxGugvRN91o6Vnb88zufQLGN98PPFAlEAcTewpacDL9BMz3kpVZDKIl1bDobZqY6tVLZu2lc2aQOC/6XG6TsRLt+/sTmhNK9uoRpLdKGmUvAnh4gm7L1BLAwQUAAAACAAvVjJb1sO1o5gBAADHBQAADQAcAHhsL3N0eWxlcy54bWwgohgAKKAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAlVTLboMwEPwVy1VvDXZI81AakkOlSD23hx56IWAekh/IOBX5th76Sf2F2hgChALqhR3bMzu7fvDz9b07FIyCTyLzVHAPzh0MAeGBCFMee/CsotkGHva7YpurCyWvCSEKaAXPt4UHE6WyLUJ5kBDm547ICNdrkZDMV3ooY5RnkvhhbmSMIhfjFWJ+yqHJyM/syFTeQGDDS6jr2MwhsImeRUg8iB38Ae6fZlW0AQI0oHZ7amzFuNTiEemiK717wMPcx56NdSlNRjyWNzqj0poRxapXlTNS1/omf8lEnS2PBG+ATWSQiaeKbceozU0pvQITM18pIvlRD0GF3y6ZtuSCk9q1Jk+KYulf5u6yq0Mt25OQob6qDbSFW2yRUoKB8rJ6UCX6qlXJ2pwayTRO1BgZdSwDQul7VMIiss46ms0pdx1ep6zmZrLF+3O9mXQnRM26+fo0jTkj+hD1K1Zp4FPdi8jqViypk+o/qt6T7DXbe3ajjMUk43GSsZxkrCYZ60nGcIsDfQ00M9DBQNkDtdpTuV5A1P4f738BUEsDBBQAAAAIAC9WMlvBQU9k+gAAAFgCAAATABwAW0NvbnRlbnRfVHlwZXNdLnhtbCCiGAAooBQAAAAAAAAAAAAAAAAAAAAAAAAAAACtkj1OxDAQha9iuUWxsxQIoSRbAC1QcAHLmSTW+k+eyZI9GwVH4gp4HZQCISGkrUb2vPe+Gcuf7x/NfnGWHSGhCb7lO1FzBl6H3vix5TMN1S3fd83rKQKyLPXY8oko3kmJegKnUIQIPneGkJyifEyjjEof1Ajyuq5vpA6ewFNF5wzeNQ8wqNkSe1zy9YrNds7uV90Z1XIVozVaUW7Lo+9/QKowDEZDH/TsskVgTKB6nADIWVGqcMr4qxIsf2UmsPg/6PdWIjuLBicTcUM850dMpgf2ohI9KZfz5GLlW0iHMhDKUnbisstu+X8NgnSygBemr6EbWpZ/0n0BUEsBAi0AFAAAAAgAL1YyW1THejLHAAAAJwEAAA8AAAAAAAAAAAAAAAAAAAAAAHhsL3dvcmtib29rLnhtbFBLAQItAAoAAAAAAC9WMltDIIeIKAEAACgBAAALAAAAAAAAAAAAAAAAABABAABfcmVscy8ucmVsc1BLAQItABQAAAAIAC9WMlsv3c58hC4AAAoWAQAYAAAAAAAAAAAAAAAAAH0CAAB4bC93b3Jrc2hlZXRzL3NoZWV0MS54bWxQSwECLQAUAAAACAAvVjJb1YMSKdkAAAC9AQAAGgAAAAAAAAAAAAAAAABTMQAAeGwvX3JlbHMvd29ya2Jvb2sueG1sLnJlbHNQSwECLQAUAAAACAAvVjJb1sO1o5gBAADHBQAADQAAAAAAAAAAAAAAAACAMgAAeGwvc3R5bGVzLnhtbFBLAQItABQAAAAIAC9WMlvBQU9k+gAAAFgCAAATAAAAAAAAAAAAAAAAAF80AABbQ29udGVudF9UeXBlc10ueG1sUEsFBgAAAAAGAAYAgAEAAKY1AAAAAA==", type binary}, {"Export", type text}, {"Zone - Zone", type text}, {"Zone - Territory", type text}, {"Zone - Cluster", type text}, {"EVD Day", type text}, {"EVD DoD Gap", type text}, {".", type text}, {"EVD WTD", type text}, {"EVD Gap WoW", type text}, {"Daily POS", type text}, {"EVD MTD", type text}, {"EVD Gap vs LM", type text}, {"Export_1", type text}, {"Sheet", type text}, {"false", type logical}}, "fr"),
  #"Colonnes supprimées" = Table.RemoveColumns(#"Type de colonne changé", {"UEsDBBQAAAAIAC9WMltUx3oyxwAAACcBAAAPABwAeGwvd29ya2Jvb2sueG1sIKIYACigFAAAAAAAAAAAAAAAAAAAAAAAAAAAAI2PQU7DMBBFr2LNnjpFbQlRkm5gwZYbOPaksRp7rBmX5m4sOFKvUFMQ3bL7/8/o6/3L51e7X8KsPpDFU+xgvapAYbTkfDx0cMrjQw37vl2aM/FxIDqq8h+lWTqYck6N1mInDEZWlDCW20gcTC6WD1oSo3EyIeYw68eq2ulgfITvvlsqf0pFE7CD1yURZ1C37M0VIFDc+CLea7t7tuttvRmc2wxPCL8k/B8SGkdv8YXsKWDMPyiMs8lltUw+CSjdt/qOpe+L+ytQSwMECgAAAAAAL1YyW0Mgh4goAQAAKAEAAAsAHABfcmVscy8ucmVscyCiGAAooBQAAAAAAAAAAAAAAAAAAAAAAAAAAADvu788P3htbCB2ZXJzaW9uPSIxLjAiIGVuY29kaW5nPSJ1dGYtOCI/PjxSZWxhdGlvbnNoaXBzIHhtbG5zPSJodHRwOi8vc2NoZW1hcy5vcGVueG1sZm9ybWF0cy5vcmcvcGFja2FnZS8yMDA2L3JlbGF0aW9uc2hpcHMiPjxSZWxhdGlvbnNoaXAgVHlwZT0iaHR0cDovL3NjaGVtYXMub3BlbnhtbGZvcm1hdHMub3JnL29mZmljZURvY3VtZW50LzIwMDYvcmVsYXRpb25zaGlwcy9vZmZpY2VEb2N1bWVudCIgVGFyZ2V0PSIveGwvd29ya2Jvb2sueG1sIiBJZD0iUjM1OWQzMjNiYWMwNjQ1MTEiIC8+PC9SZWxhdGlvbnNoaXBzPlBLAwQUAAAACAAvVjJbL93OfIQuAAAKFgEAGAAcAHhsL3dvcmtzaGVldHMvc2hlZXQxLnhtbCCiGAAooBQAAAAAAAAAAAAAAAAAAAAAAAAAAADdfdtyJMeR5bvM9A+wfpJsB8m4hwdN1Fh3k0Pj7jQ5JlIrm32RgSRIthENcAC0LvNr87CftL+w5wSqgKiu9IzMrCpOU9QMyG5kZXlE+OW4h1/+33/939/989/eXJ395fL27vXN9UfP7GCenV1ef3Pz7evr7z969vb+u3N59s+//93fPvzrze2Pdz9cXt6f4QPXdx/+7aNnP9zf//ThBx/cffPD5ZuLu+Hmp8tr/O67m9s3F/f44+33H9z9dHt58W392JurD5wx6YM3F6+vn/GF9W8/vri/4B9ub/7Kf31zdvfRM/fs7P6jZ6+vr15fX355f1sffn3Hn/e//z8315dn52f81+8+4F/wJ3+Jf32z5A1fXd7evr6/uf37Ya95efX27v7yduVL/vXm7OOLtRQ8fPjs3y5vvzvgDTcfr//wpxc/HfCCT/73xwesvn76sO+++ZgrWPmGj7/6wwHU10+vpn7z6YOof3kQ9S8PZb36igM24OWBGzCs5/o/fXWAyODDB0rsn27+dJjE/uXu7F/XvoJys3799dOryeenSf/6N1Bu1lNfP33Qdx9K/cuDqH95KPPVVxxE/oEbcPH6Ckrniy8PYCB8+gAK/vDp8/WfPEDfbT59gL7jGw5a90FqA5rn1SFa89XBWpNv2Ci/F2+/PeA9N68O175rX0EGXr+P9dOryd9q30Popw5cT3/99Gr6t/r3UPr/7ebuQCqef395fX/QO14etIsvDxWn+oqDyD/8IF5iAdcHUvGHy+9eX10d5yWHrghE3EAzXX97dXkAQa9ebd9Beta/h/r+sE+re/HBo6/fuvxp4nUvIS63l2efffbZBD154gVf3dxfXE18Njw7++DxD7Z+9C+/tyZFCTEMxkaRUJzwQ39556OyfXqwwcck1omT4kNKY0+XzdNmcJJjCqW4krwvdvzxLSnOiwnJDsa4ZF0KEkefNu0ytoSd2/E3r17xadewJSUFF1M0Q7T4twE1U5tvhlJCdIKHQ7TZdOg2BceUJJlkAz6RpUySElLOqQySBN9ijPXKhq5yNdft/Txue2QBLJm7E8TnEJLPYqaXfB4LdkUGh6PNJYfcZzdrT8VvT28+zTIWcdwjMUtZzlhwfPYmGS8hmCDja90KS/ApDwL58uKK91khvd1UN30AfvNrvMz0aMV2JVtMePiZ4qRg29HXNRtFic/4J4RsRbz3dnLt08K4jGXmycnj096LNRFcFl3OxaQeC+DhkiyONrnsJKRx0s0j7c7aHAbwrTXYB+X1i8TKHEOPz1vGzipibxWN0LosNuRQBMbCeLD0NDXJZHHO2OICBCwpJ3xCqW1Zt0jVHQI5zJDdouj+raXIkooMxZrsE63ipHYygxdxwcZiYig2pzh+xg05Emg5HcQoQopscJPk4OUlDXjMQwRhucafbtkZ9jBkEFMgNCZN60uszxmHLUpQVibm3tvnqpUwrldOBBunXvDvz7/44+cff3L2+f/64vmL559/OvGaeAD63G5RiBIhW4O33gWBrhzd0QZwJti3gk9AtcVSRk+rEfIoCRwGVQiriXOehF9QBCJlcA5cEI1PilgdCjjnrfi0a9g8nV0sVGuR9jHgv0eV4NPmQ/kF4yADYGPowdF3NybV5QICKga20DxmkhZbMggexGWKVfRRs/4HIc5lmz+P3aSR9kLzgBOgpgpJU25bYqyXBMVZiikRaiiMa+aDIee8Re9orVOsYxHTNWhmIdf5GHPwpRQhA8IMT2PO4uHmJCygeBhTzc1ZDjlttKMPtJAz++Yf7OI0BukaSiCaAgwByXfwFHz0k5Zy8ssWssw8QXlUUkA4eDdcUA/La8YVWmOhreQEpkm0nxqUegScQRKOf4gxhgzcA/x7IsC5WI/PWka7itBdRQurDBBbMvgWz0NIHeZLEKgM4YBzbw3F/GcX2faEsX/GgG8T5BHfNM23voBnBrAb+AiMnia1TQWcwUMhOOtBS8Dm9KiJBkgzQAFic1wnZMN3+oG7YzpnVJcJKQ/QMwIl5aYtucB6GzvAicTH6J/0xX+eOgnj+uT9hpph4jWf/3hz8fXF9ffKxx9WC5/NCffT4QyS80pAKz4pNKimAoMAixaSFv9KT2FBgyfhOAmECd7Evup9eDAmQCLwixSTQ/Rwukffm3cUTtS10wfLl3gCmjfPQVHROYILm8RQN3a22EjOJkeIDrRRUgTtiVzj4Z0FA6+xuOwL/jROh82U3MHnhNOrDvveixdjyFU7PJOJ4pOqgg7MOToDNUX15r1T1ngO5erLYGB2rC0Wez3uV+4y0oS3soKR5DR0L2ImWc9M2boEjUkHBZ8Yp8LBb8kCM0xoZUmIsnH17UXfXvzaPYbErBLBTa0uhyeHB1MI3Fq/b3GnQFzrkUTudbQO4LbkfTO/QWTjf72QEfr8vnlt4AsrZISI+pTGLbI0hpNmViIk2rrg9plrw+sb7OScExlCdin4HJRY2mzJ2Hl4pabtLqChvPQob+TOluQZm0zACCV4Ow67n+iIgJXOG0f4gQXs+0anFL7mPLPNQMAm8F7DSFIMimT8HtsRMpwpZ7AnilIBxoM4J2NsjJZRXZlmVGK8ACkEMEy83Ur7mHCzMhN8tEPET+GhKNHEdmUhWMcouvMlZUVqc4aezEOBrwpZASU9cmfog6pixn27Xy60e/7Xi8s/f3J3p2W9b8QmZlfgTzK2nUTMPjB4B3g4iGKpPB6Bf/I4bk+teYOmAisyQACDgR97H9maN3ptwN5JwN4AK/6I+G7mMk9E98ZQGFJB8YFHJYBg4wYoPnIudjc5mAMPfyb0zJ51EWIDCix0ToLYK0RkakkrcJJ5sxFHHKmVAG/hFs/kpKfdMFFgjgF6+Gy1HQruiIb6IfsQeDmnuLirwN3MJcrxaV7EQbKSg+CQw9XPYmOCB7xvQTdEYDVuCIBE4CFmOhwH141bhwbWweI2/zP7N9ybrewdiQPYBpCOORcBjNIERbGXC1mgz+UbqybFpUHERcAMmCo7Lg3NMgCdPHxPsRlgMWhxoi2uA7Dwde0O9jiJktlwCK5bKP5zVvBEuu2S3gA7hsIS3gw8Ae8b7m6HkARgAPATiwVoGotxnU74GvADksUlLDNRLSvgJ8E9h61xgRsGlvKKjGK/sgtgpcC7aGihnlR4YFBiYVgv7sI++22EIsLpGBwzaiA6XVHLWA2I5BU03ZZ9W7N5qwOoBT/gAJxnzlTvvV1VsAPodsn8BQO6H2+ub/CL7y+m7TCgsRNsPrSOtfC+e9G6AAcgJMa9eUhl3F42ZgKnmsEmeNTQM1YUmnPgVF67OvzII1GCA8DcvBUen+TN11uG8gf4gomJViNQ6x3kAsc1wXMVmPfooWymDfF5vYeDfa33vpBKb/evELf7BJctDnBHCyQ3F7uvD1ajuWV7PJOLYqPvLFOm8oNxNPsy//Bg9NCdVI6wKlR5xwRz81YoRyd5ERfJAVwEOAF7QqVewCga25/7AlwCC+BgkWPMY7mDKwCdEmhq6QNJTjEJ59O2pfpnGQYW7wCwhmgzyUkTEuUAlp1/n8M3z8E2+jw4Gyyzy3yXq0KpcMUJlBPU0/ixbnEcQIJNA+2/9QZQQX38ACC3WLv2VvBEeu6T3gI5D2mDKwKQSKy4D4reIaTYkpksluiYYO8P099LJa/F5gG4D66UwCUHGs4KkzugM8ebpOy8Y2xR2bnzMAQHnAwDZiwAWOrEFKsFwbcaQkBnDaP0mpiVUAYBo8YI39OYbjCtmASwhlcz71OcFqXDL5yDhLuY4cykkTuNPYpHtcEOkDv/h0Fyf7+5m7S+LrPIgPncwqTWtK/b3sVwvI5MIUNI4PEoKbY7CKOEwCiRA3/Aou1HUbcqA/ouDJRusEcO2sX7Khw3c5WnIXsrgsCFhtHkeu2SlPSJBssVQ+8c2tEDLZbOXRmvGSwwA6yv5Ey1p0YRvSugGAqGGQvWjeX7r4RyC7d5JjO1N694v8frqcZCLqpXeg58atLApBZPK2kVSlbBuZmrlJOQvYiZZCUzMZwYi4etBUuBQ+jKKBiEVgcIyTtDvJpGYibLEZ0SYWqoc8GX5kdQjE43bAAzF4SJCtnWBHZtlZrpWcQIfXZ/eK6WdwzRAVlUI9iHL/AhjYvUP8AC2etpBlvrlmwJDM1HsJgvXmGHQ7DdCo3bXURDve9TvwPv6pshNUDywDQ97g8sS4DEBFCjMsWJZLC9N7Y+ZstahsRLTc0CMUDG/DnDFAnefypo9NwNLG/IhFUgvXilZGQHKknhWdARxaes5oqcl1QDgSYZi5/QF9ORNS4OEBeuFBkE6tGrRAM7g4+gZiwINwDS/bB7Tzm8nzG7V5+9evHFq+efT7zmGKUcyWQYIbACONsrYtmkitBbsDBeIfLGsVOtFUzNDYVjCvThx5NbH3MycwRktwOvdVh2o2RFHFrHMWe5J13A9q4f7lTIYYCRFHxHGVfRTdWwwEvLUHIOno1XRLVJW05Unz7h3T4yIjRJueNuwGwHKNKEUz1JEceSnZ/HaK1iKrDbsCwOK4AmcUpuxvYD9GRzHLCXIoXZyEdIN1/LbTtFwydZxiKWawsQl/AcqYf1jXDpAf/A/kWLQD2iDheNgbxEGGAGcrSKxTVlHDIesmmJNSZ6ekUBVtg43n1PZnYr3/i4W1OfnfzlIh6ZJxiPr2Ymlh8cU/Y88zz7RaSJTqCnnQ8MZE1XbTByA8jDfH6wqqI2Dq/ZWKazZ66hXYLtLKGtEI68r4z0qyPzZzu9M/AgMEcEewHVlKyUA5xUQNvjhTHLjLWZ4srINcLuxgDq+cHTksAMTpc9MJePrgnAaRSicN9nNVgaZqeAcEsEOs3JgfkhgzA5LwncAaXLQLvUVKvoLeuzAZun63aKSwbWHp6fZOxlp1JmifYI4/z+fuPKqQjiq9dvvr55c3GtfPxhtQ7g3HuBo5Xg7EF6p2+CWetuuZm28BYoGEVmmyIIaD/GrWuLimS0IogANs8gg4VB0TijBNzXxRDnrfEEND88x6Iu6Ate2ZZSGOXr7XEOrPFLcE0jvPGOB05zHmlsjIG0wVEdUV4btWVqkMp7S1kIbqSiam38cOkWz2OjJoBooSWsZ5cCXryLVpxyHgIvSoZ6NNgVLXd8Xfxw3irlFFQvYiVZyUo1cMDrIx5O9Y78fi3FlmSfbcY5OuZ42yLlGDl+ufSvrI1lFePjP1kNl/fu7CAvMSVneG0Hs5mjFsrQgpTL2GEG028JFxzvwCos1ge43E3NMnAuYEPFBiAYn0UxotswIuyhSyzggpUGy4ny/oOiiEsVQn8JT7TnPu2NDHqKlgDoRIuTLqEXo8aeQ14Kb6FZ3aZdX55IFJtDlZJZlAFEzdILJYDniVZBBdQ+r7+9kvJqBnHW09cjBdjhTtLBQ18sACyBzwemhb3Yv+TfPOoisTDkJ4oj7lOKLpt8BuA8CEEJjhmIQUv5w9ICOSgzTsoLjS7FfdWwE0H8h4F6n9zd3dz9+fMfb67eXN7dXV5/f2YnzTVkjXekA0ulWFc0Hmlt7o6ZhZtsdIGFz0p0rTHuyfrM5kCGVYhBy/ZgbDrGQdg0yeMDR0z/m7nA45O81X7CBO0BzB2EwZNe4QJeChgZAeAM1U4vvxKaz9Fw0UQbtsBS8B49KluTnaFvHLzVY+G9hfs7j4Ha62I4vRaOdcAu4/+8VhRxTkKw0dB9gE65aG3gVsG9mYuUk5C9iJFkHSORYuAQeNI+McPd875KpZiJQvC8A3N1soxkOC2He6EPC8DkrA72jLU6gUVQrNCMZECGzBMBBkBD2S813jypyNJCZuhy/GYDePHHoJbkUrOKeyACaMOZwgtRBp2dVvO+RXoR9hgKgPWVzAosSnO3Q5DeYlXbX8IT7a5Pe3PEYJFYgDxdKrWqqndb7CGEOJ8A1c/iei254zRC2FaAZcs8yox/ubjfVmSzz0CjofYdNY59v4LCUrwEL7ZYgE1hhQcQbO/74aQGfDf71EQnQavsAG0Shpq0mpyIlofaLgyMwX45FjjaMQKq2SkCaRsNbyIgNJ36nVlaYQfo/ZKuipfhPDdpph08nuDLgxC5sfSld3CeJSS3/FiUoIWpm0BZTuxtAoMXgEKslkIako/Md8629gkqs2Iys4N7s5Z4ApofnoNvyQZSQxB2EAYmm4Z6tXeTSYVODU2v0jy20ZbCPljJ1RomG6OaTQtpcFAPESfHXP54vNzAZTs8k4l2urJIhCOfTclMr8n7pG85QdgIDwqVfRlc0TZvZWxv1irlJGQvYiVZx0qVYpYDFrbH8o7p5/v9+DbPpmyAYGBjEkNWrDI6AtpL+8GJfQq9deyEFGBrJnDTnNqPtW9axQ99rt+8NoFPLNxNtgqGke5WiNbeAsATybDo0ind/B57s/hsec8L3JEz2EnphHNYZG+pwu2toCHddknf6c4CbGEsbzIytKOCGna6RfGATAHYxlf8rFLYIvhEcOjAlRDEpLUMsjaWzLiEY4auHuRmcUjMyScALMc2Kr2wInbBQxEJi4mpBjTPhMhtYCZzYbBuRsWtI4YGlIzwfMEkGppmT4A81L467EPr98N/y0V5N6p3NLQ3gdKOPhkEOx1sTolehjDTdLIXLl1GpiNbBl2tuPHWCE12Q2LjD5bG2zQSBWrosJajN4JjB0sDRlWw2qHZffOWe8IFPCpMJk1A0EIUyK4fd9YaYQfTZvgoeHgkhLBLM+QRdhQsSzmDNzbdtpd3UHCvCtAmlmq1/qWHpfYt2/Z5XLaTdQzbYF201gfWH0xORjgPWHPtbB8y1Ww8RlrSel7bSRo5xToWcVzb7HUByxnrmGTPUkQOGBDFRd9Gh+BVFE5dSEmY5KPN0FiR1weL1Z1eYgCBLC+MvIfJtWo262bfJrfpoRkTM+mLYy2ohOkut0qUah3HzJOTxyQ5y17sAFDimRY20vDnnZXZ2hhICnMEjZK99JjoB7gQ2QuFzVwsCxYOl6nRVL+lCnzOInbW4HpraHP9HO9WjS3MWpCRItl3jIkk4r/KfLAV083Xjy+uO8M3wAHeecYXXGK4eJItA/bC5QGbWPu2TI/qOLcDQF4RtqcEOmbcu8dogFmBvaiMcFyNgny3bAzcbfyQeFUOlo+djeFaWW8jBQYRCpNl8lOvd+Lx2jB4Kwl6LCu9v+xyfRJGFcppYOKsQuFPv/jjl19+MfGWY1SPREaErWc2BG8D43jvpcad9byOgAEsMbCnRQfqMEqQgFpStNPCbXFKUu8khGWHToH/h+LLecs94QIen67d0mSAtoGWHNdMbfGIT4GlZoAfbODUMaGJjehdsSYZqKiRTIodgQ0JZ8oOcjWBOoliAg9DmMs2fh6f7SSlcEYLPGNYeXjx0yMdzpmiBkxteBPH+4eRoOhREOa8Re8OnTvBOpbw3E5y+iKmw1M+OFeAMYMxoUxPaIxwa2qPWXBnZnfeo0FMDqyaIvUhIQh2iZ3YYHhCDiN9nXb3uXtszCZnpCUVT9eSzSumbfAk0FnGNvOE5amkhD3igDJrXhi4pl9SEnk/XjjIEqpNgaWPQNOCZzKQFysOEguATwQ0l2ryectoVyHdVbRQk9xUGMiEix5DN24RHC8/OaIQatp1hqudQHB3DhiIvU6vZOIkeGi6xiVQRw1i2eMfGHJ6Zh5rtS2ejTEzk5NFID1qgNmL43gPxk+t1jJnC30z5whBCzrOAukPncOpRiL8mFhhNj0b0gBUM9Hg4QI6zCj+m6lWwrheeZ+hZmcQyNV3N2+vbt4qL9hwcYZ/l5l3W1gwqJ1Wk/zG1rcmi4F2Y4vNXnohIFdi53RoYBGx+w2JNizjmR03MNYe6UaOvnVlduGsFR6d4oenOAMiULPjWRhVzQtsLvWdg1uUHKUHnl13OEKxYGoWF7PRZwnavWbNFfEDuyaawImyR2sTvXh/53HQTjWJZz9lFpPhK9RrUE8KwuDEcl5RzMrcrZXZhbMWKScgehEfyWo+8gUWxNU7ZM4e1hLrAAsz2AiMxpywkRYyK26aOzrkQYdzwLgwegFzwVbVyn72y0jwpuJDcBz6BXyi9T/RbvqWMcIMbt8QDqRqeaHARqU4jKT0Fmg6/ALVJrEcEM0ZM2ou7YZ/WBnnBmalsTZU685+WG7hQkXQXUFDuu+S3soeoJvJxDeW17FKDezTXbNx7AjF6WzF0dP7OUWwSR5gz0V2w+Gw5OK0HrG5FiMNloXqnk1l9ZbRAMmuzsgoaUYJi2W7xwzXA5JBpK2oLGHuIZAmlgXfSqsBa5blLTPgS63T1hKzEifS8QZ7O7Ct34yprxKqljl++ch/K6z78ma6WbStUyto6Av2XJQ4b5PgFmuKkY2louNur2i2omCtLcsuOH1M4b2ANya2gCyJ2epK9Hgdnpu1whOQ/PCc42TXKAPnQGRvg4IyGsDsebnHxkps/SydVo51xATcGp5GTZNRkSW7F7s4FN7mZDg1I7kkaxHdoh2eyUNtCiE8PZjfWEcUca2aMS9seTJwjFHhvcLIaIcDEN2sRcpJqF7ESbKek2xm7R51dGYu4X7O1cOTtTgS1hgrYzPCONIgY0W1iFJYuIPqAps9pEwjBhtVNFM2J4HQMZNEXG2zbhj1mwsQ17BDn+c3Zo0D5wZyTRLOu+82rzOFM79h270nl0UlDrhFdTR8OQ5SCweslk52EKhbqG37C2goTz3KmxMGLMIhs92/B0wbqbB9hxBwvGPJeAFX4YjUFp+nEcK2XqMQhCW292Q6nCaEsD+e0wrgLFj2blHVC+e7cYoANAtrXELujyIBAMUqnRQ2k9D6LNY5UgK9luGCWC0Bql1YbUfFiXWJt2zaVEbLnM+A89v8MyODsKsWdpHdz5FCeHpk9+rri6urCz9pmT08Q4tjYjN6Xrl3mpNA9Uiwkf4Czsdp7X2a0BdAEnSnoR7l8FJtJCKcCagdU3IGP+exYNJqeDdziSegeWu3PNuSDg6aLFrfKbZmY1J+PaBB7VYwlnu/F2iBQqqTEdmULmkF9ZbTSwrTEguvgscGaq8d3Ltsh2cyUdyFHZm3WFARVh2QzCGW0P8+U/MkLZC/bmbvvBXK0UlewkKynoU4hYRj3DmYi+1utU4oRH6sQSxSUtw3KGt6Ris9vB6JG6dkvFPfO80gbIlPP9Q2vFrbpmVH3mfqzRbCszJ+YEVE8FrnuHeGHrDtgLNUSTCMnRbRgQNFhlAvpkyM8QQtoheK+6xFNNS7PvU77V0cxyDxmlWYydqrWWTzKwaw2NslycjYs1NKXBs1jjawYNqxex/dJQ1FsZhi8AL9wEkhVos2nLvBsr6LJS7MWYydQR0MasIEZM73dMByopfEA017wOXMuSaeo3RmdHLGfhhmiGJ1KWtvZv/tMMi2xUuv+fSozD+Ctt3f/vdhthfPv/zqiy8nXnKMdD4bnLHWpZrLmoJSUtt0I8h1jLXnEBfOvRh7ukn7Z05v8JFTAeG/TFZQZI7zSR4ohNX/4ubkWK1I6Ju34JMuYftuB3kB8hsgPMJu85M5fTVmz9svXkhkL+Oy85QwAkeQ0sg0Zs8ZJlOUwFEH9HS8nGB2dVDuuA/M6Fu683NYrdWDUnsVMGMjM0dmvyDunc0PuTaFMtEz0/5E/aDnLXon/fgU61jEcju9h+fzXO0H7Wr71VDSw/Cy6R6yTlgaPIivgZlstEzuFUl9Tkli3akbqeNKODyPbZVtpyFtNw+Jl9SCncoxlDr9fTpHazrddxnbzBOWxxwo8akwNpesIa3jLY2bpfnaFBQMkzk8QvOHtkAcuhKICN4Ic1LrtLzDRWs0o2+ZQpm7jJ1V5N4qdlJxYSQMW/gZ4NIo4+f/RE7KHMPBOaEcIDzSMenkkrtTVEFEVl2KDCwZtKTuzes5O5gjR5i0BjvTSV6FRQwxsFoZGq34btod0xdBDNssYhkuTBeQcOp1ZIJhKA7cn+YUywBek/EDk0Y03+DJrwR0H6Kvn4il0yp6gWIJo5rlPQacUzHCFxd3951Jc5bdfmoFFABJZjeU0W1pe0RH1k1yEJvn8U7fKln4TtGxEAteVlQ7kNFbg5M3sAC4ljPNSTeZewE8b4VHp3jDR47zvO3A6d6BpZi9FjLsV1vHxUOAODN+klhTM1uFsXroWjqdWhaGwLpAHjkVHXhgbPLa2tvfZds7l4Ga+KBnuV3msMnEDlpaqCfmwmtJCLbFWvMxe0PPXKMcn+ZFTCRrmYhtOVyqHWF8HOlIvOUhsM/AbrvwTGqdq7JpSyKE2lCcnXvfHDz4JDif64j4/aqUzbOd0MX4p5S/XnzmXb7eEJkTCx5YKMvIMK8jOi8GczDND5YxYfOL0grlsSugY5+5AfwHq0scc2Ba60iIcLHId1fQkB66pO+2OzEAOhIKvRal7XGTeQIdGIg0oLzTSDbqKaWtobqOqCqObb8gRlpXZ+8lsBu2Zct4ybJfeL45M+xYnW8PShlqy0rBQkMAkCL3DY4J6xz3iz8eHmQzFjox4i3+H7C+uzBsG3A5wJXxkGu1m2dJYuNQPJMnjVYqLIsUwE6w8L254T0IvL26ub4/+5fLry8nzS+gh3FhYE91BrqccufwZE5zYcYwWByywOEyvawgy1FSHlgIIsZ8TzUhxrNRKCxdziEUHPHxENzMNZ6A5s1z8ExidgPUV6Dx6xZlsAEURTYn9o9XYg7NlbRhvbFL8NkiZyVprUrhRQkc68L6sdrE5FgYbvEGz2OinZ7PluMvWO3PcZv6fV1mj3fGbSjlCRbmiFUZM5cpJyF7ESvJWlYy4GKYIwaTKkLTpl5YaNIgQ2D1aKQ/cIyOzzARPfKs4TSdaF0EmWOtBzdv6lgaQ4DAKVqw1WKCWgugnMJCRpjB79v9kQQIPUjIKRkOc+0txDlJznpeoMbqok1iO5watMPAeRTMs/NKs+JDsN1iVdBdQUN66ZK+c4GZeAftCRpL1IYwNp5wZJNl4BnOdxrpVH1KAWwwkMuc7QIiIhBm0UAb+1gLwJ0B60Yylpq/MOC3VjjezNX2AF0C2HqArSoBnwvOUCvwY79ENnFmNxjGXnuvxQc4q1lYqBZGGgNs1hUsZ5iy/zeLvmKX3L5G2IF2/xDI7vMfb978eHE9XZmRPOfSczp59GyvqYSimzEeHGfGgS4OFqtvKYJPOeeaj8kihv3Y9ea9hf0pwkP+C+d/HzF3b+YST0Dzw3MByhQiOjCszTxWJWTUTvLgmC/wKPQcN7s/sVyEE3xc8Eyq1Xqv2wi+T3EgdOCYt5FY/Epgt3CHZzJRi+s8PLhYIncy13x6RY85x571Q0jUZoZxsePhupmrlJOQvYiVZCUrkWQ446kOIzSmODH7I9k2j3IuvLFDYXAkejgWx2jvbLUDa6d5AO/Uy3HDCQYcnzpO4YyMbjAg/P3ISIzNbFimHc/43y9kiD7bb55L3rMDc4IZToUGvA8GkqttkTmix6s5qxvoBQPvA5EJEcesiUnLsN1ifdulvyE8dghvzjcyM44AJVaG6U4i4A1xsKzPNYHlrlpW32lksK22sZytHaKA01kcodDBmmycozcggs2Y9dKMwBqkwkwmT3bv5h0z/bBIgogHKK+oVYdnL2IGoGzme1jOpeuvLLHyNwRfCosD1ZgkO2cPNSEdvCpK81RZohR28N3uEfxC8d2L29f/8fby/vb15dn52ae3F9ffnr26vLubxntkK1ZKs8ad1dLdi0I4+REgSNLDffy0EOU6cZBdb8lpKapjbzMwk2WKMcyNUEccD+7NXOHxSd7wrgS2HB1CDdaXXiWuHWyCE8N6zNoNrHO5EGqDTTyW4fuz/ZJCLePuUJODhwkHOLUjOR0rsd7C7Z3JQM09LNS8cSwkgL+GDdfG6LHZsCsDYLopzJlTJjWtQnoz1ygnIHoRE8k6JiL2CTlwChXTlUzSyDiHi5+ASzmwzTJ4fYyrWOmE7x669cOo+ADu5YAIzvDUUGjvYKxLAWwHy2cTe2lovpFyPbuQE/rc/vAc7LvY6OBpBuJOLbHoaR2wxZ5pIrn4Orhe60S1eT1T4ySxPJZzM5LSGvIQkLdQDcxYQUt67pH+tDNswMLMB4BlKD2j9Op7ooMd8tlHi/33Clv9/pwS2JY3YNs42jvXXsZeMzuWnrqlREAaglP7qpwzGpbgz9jA+yjT7QBksDyO2/Cc1s30P+VAOKpRgKUF62OpmdLDrxU5dsOxLhjmCVq1uQp0Cst0mFhHTorKVZ4sUgu7F7TvS8+8T7764o8fT73kKOUcniFcpsSCv+EfjRvEtjtzkcgW//lhgOjY001z4xILMH4ELnccNDiZN+ng6IjJQ+FIepGR6vL69MH1HLNWfNo1bEkp8GAhowM9G0nKxLI2i4fxRZdqTgeHi09TbgTwIj10mucFspKysiWmNmDn/RBwCfM1TjIHZNnuz+O3nZrFzCaGuQ7DsKnTqfbcMUfX116pCUotKEGHw4s6Zq16dxDIKRayiO/afq8LGc9RlTMXhqOts8pKW1BQW88SKgLVaMNqVpR0eL9/wfQOoTA7lvnrPkYYYqdYk1H/f3+XAM9zkqefmj3fkjdd7rGMZeZJylMtSRHgTHyGbfyCVnnS9rV1wptRRm3ZoWD87U8BWRtKiUNtZQaVeAyxGi/oWKjL5y1jZxWpt4pGaNmKEToXetezWeZ4onjTotmlGicD4Ql8fwxbsVRmd4oceBUknD0kbDk4LQucLw1+GyC5BOjarOGnvQHx8B0pbdgbURz6dvRMpPHK7HYjSeuWtY1vWM5HHoilHzpZd2vmsjEmxdr0iIWMI9cQ7VqtNaycJ0jm2Hul8bxdqlbCqF55jwHn5ITg+5u3375WPrw5Jmw1/KKB7SnY6ESBUm25QXKMfXsOhSlKXWN7A1tYvSQcPcOqeLU7HnQeSyADXpyZnTv63lVhxJlLPAHND88ltmgqAvgg8LFjUsxAc2scSsL3JuaSsSN999YlRWgiQ/ePJacaHZJ4LTP42g81spnN3ntXRhIX7vBMJmpvjWFFjKuzMh3nrOzHBrac4NmLaxC2AoXhtWp/sxWxxJmrlJOQvYiVZDUrGebqML00MsXVGu3CiFmOjlvByNhIztCaG+Pu8NhxUqZ7v9RuNtj4HBPxFW/x1USv8b9feOx95t4ul12X3MA7gDqstdtljYU2vHSDrStjubxt3DARwtQhDzkGJf39oKjhYqXaI7+h23bobrv2eZ8K7yLZ/w6OSq+ZV/XdGHOyifPhtG72J5Kz9v60AEaB7siFhpEpUxsYwvm5cQiZXJK1rulM+sts1mQifLvo+0FLy3H30EuO/V+xh2oXRexrGPDlpkCTST87D0frYygcxwOvR00nhmtgCge5JpYqd5l/VHG8b61eDoNqb3r5fZ4NIYMb2A6EbRG7RQWeExtsAdqNMP2d+17G1Apv9fkpTqrdP5INigBugIQW4h2OU1HK8db15pu3xBPQvOFK4RTONBD4wW0ZQVLvIjVWcbFbQwkcezGj9zJNawy25tvCvdQqyiBDTgYOa4oPfYGPBdUWbvFMLmqb8/lUR5lbXhzgI9qdQck5D2w2BY/YAm0csfp25hrlBEQv4iNZz0eGc11rdAkueSSbKArceW/YdRUksyhupEvCcqSmXXLupPYBcVkWjxvPDm9qdkP3ZBiDMQamiv+V9ntUbNapt55ewgp9dt8olGQkOrbsZomhNt54JxveMHrMYba2JsdNojc2yQ2sJAgguI4GPDp+W6xquytoSHdd0tuyDU8MwEmwga3vlAyxxjt3rBpJEBReKpt9jj6pDLbXroDAhVUTUAhGZcDC29MhO8vAu15aeF6LjaPNwuwk77VmX818FpvZ7TBi29iUcB9yblg6xVjyIAULY/+9Dqamjcox83bKCp2lkfHMGxvl2Jd8EBdrt5w80v/znRf3lcIOrvvF3Pl2Sjf+8+biz19cXb7pFOZyZhZOc2DXuQSvoDO3CgwLC8SsyjoUORilfU9beAXkAQRkieZ5pT9+rniVg5VL0UAcyAJHBHgz13gCmh+e48hRuFHwOygN2LfutDT4PXUIDRO+pVutCKZmBKcwEMchPlozWceGMbzVhWclIxckK8Hd4u2dx0I7gTgoEWtqH4rkmcWtqDPgI8vblBzqrRvgyvHw3cxlyknIXsRIspaROP4j107F2aW034F/sxFQ/V6GkG0qjHAdpcFK6c7V4jAMA5+EFzVSYFm1YRhd3M1KXAgKZ8ZnM9K+Y2PKlbcvY4MZ3L7ZHweLbsIgQNUcMzEjaZ2tRMA4Fj94ydgZquFCspGsUxKRxn5hzsHobrEi6K6gIT11Sd9pyOwfAsoQQHgh3TmBnpcv4Hn2lByB1SeUvhbZJV4TJhaaximAyQJliew7Ayo0F8cMnLiR2KSGHW3yWOn8u8G5yPYp+AiEY6wB7WZZoE+Ih1keA2jZR3YZOJEUWNYZc2y3Yp6EU40ZWy0JCFMJNcsSfbAD7N6XmtxDgd3V1zfX308aZDbzTC7hjDxrlo0SF26n3+aajwvNA52uNUVp5FaYQUncIczVTFoEjMfty8BehnCa2ADxeKBu5iJPQfSGn2pXIs8rhmjx30pI8mmX2ZgssAFSqYLZI9eyU5fJnk0aoEO0CSAstILVgDOdAf04wPFYuG7xDs9jo92yXJvwHRbqv4Q0UlG8eZSKJg9Mo4SHr/X6Xdkzb9Yi5QREL2IjWctGXkBsYMOtwFCKgj6gPy14nvXfgQ2JjlKN65UpmoeP1WD1X83ZcYmhauUAtFqNZUc+g6+3Bx6sY3m8ZZCBgcM+EpXAbH/rhDWeRR8FuKHcR8dZBQBMLllGo46O4Zar1f4anoiPfeKbc04shWA1ghThfX+PlMhkLjYaZS1pCfulHyeUuLbpT+YsNw/QCpBkR5qJb0TOJvFDjni5YfuHfYC42TdOpeVThE9Atd0CCssb5si2fIa3CtrINfw6Am4FYxmnd0bpfdyWnOCYOSQIao/FgZrcBeC3MFR3ByaXSY3TL55EbXOuWfPa6ocnKQljOaXBczif49gRFtLL+G1Rk4Jh2KPK82IZQHr86aeczyCR8gUnlGHf/ZZdLSUc42qs8QNzPHLWGjAdWhAxb8EnXcLmaQ6g5HjPga0wwXKpM+DCWGHnocyE2KxM+WuSf4VNTSmi7H80lpLWkALvrQ6zZ18NfIHmSB1YDbFs6+fx2k4oyhfeMbJoNHJHp6crWMObKIAXIBigBlGahR5cDTFv1TvVECdZyCKuazLtl7EdO6Kkh3GRNkMKtJjXlhq2c4G8sH2cLRw/2t/XmfUQTNPqF0TATBe645Tv0qmIUIhrM6FDYXO6kOipeE6ln1z85EEt5Jt54vI4iidENuEfck3dd1EZ59VkqCcmkLOvcoQd1SZIbVExO21nTtwLwlRHpRTr8IqIpcp83ip2FpE7i2iT/mu7N4dTFwuXZFz7NwURgFo4MV5UQEymOeUUQrszUYIFrrkkBiGdG2k6srProAJsA4c8ecb+FJT7eJ6woYFtuGMR/k+ZOdqW39RxoExohAoRpbx58zgvw03ta81r05j61RDCIU5M/oFjZYp2NbNdq+XkYvgKFs8GNoLu6oB5OiWMK5Ud9PfA8Y8wUDW+z3/66er15bdn372+ur+8vfvw17/67Pqbq7ff4q9+Y3979uXlT/e8JL09A8/Hs9+wnfEPvz37H80v7Nlv/uXt1dXHF/eXv/31r+oDZ6/vzv7n26u/1w/90zsv+aezm9uz52+/f3t3X//861/9++XFLT/CP41hge3C8O+7Hy4v7/FVF6T+zeXt95cvL6+u7nb+dHZ7+d1Hz164D1+6jeC/+yv/4Yus/Eo+fGHt+O+euw+fa797YfF1Vvs+iy+EI6b8Mn/4wmmvdQ6/VD75HN/5XP2ly1j/wyo/2N0q/PGvN7c/1q38/f8HUEsDBBQAAAAIAC9WMlvVgxIp2QAAAL0BAAAaABwAeGwvX3JlbHMvd29ya2Jvb2sueG1sLnJlbHMgohgAKKAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAtZE9bsMwDEavInCvaReK4hRRsnTpGuQCskz/ILYkiEqbnK1Dj9QrVEiHxkCHLp0IfiQfHsDP94/t/jJP4pUij95pqIoSBDnr29H1Gs6pe6hhv9seaDIpb/AwBhb5xLGGIaXwhMh2oNlw4QO5POl8nE3KbewxGHsyPeFjWSqM9wxYMsXxGugvRN91o6Vnb88zufQLGN98PPFAlEAcTewpacDL9BMz3kpVZDKIl1bDobZqY6tVLZu2lc2aQOC/6XG6TsRLt+/sTmhNK9uoRpLdKGmUvAnh4gm7L1BLAwQUAAAACAAvVjJb1sO1o5gBAADHBQAADQAcAHhsL3N0eWxlcy54bWwgohgAKKAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAlVTLboMwEPwVy1VvDXZI81AakkOlSD23hx56IWAekh/IOBX5th76Sf2F2hgChALqhR3bMzu7fvDz9b07FIyCTyLzVHAPzh0MAeGBCFMee/CsotkGHva7YpurCyWvCSEKaAXPt4UHE6WyLUJ5kBDm547ICNdrkZDMV3ooY5RnkvhhbmSMIhfjFWJ+yqHJyM/syFTeQGDDS6jr2MwhsImeRUg8iB38Ae6fZlW0AQI0oHZ7amzFuNTiEemiK717wMPcx56NdSlNRjyWNzqj0poRxapXlTNS1/omf8lEnS2PBG+ATWSQiaeKbceozU0pvQITM18pIvlRD0GF3y6ZtuSCk9q1Jk+KYulf5u6yq0Mt25OQob6qDbSFW2yRUoKB8rJ6UCX6qlXJ2pwayTRO1BgZdSwDQul7VMIiss46ms0pdx1ep6zmZrLF+3O9mXQnRM26+fo0jTkj+hD1K1Zp4FPdi8jqViypk+o/qt6T7DXbe3ajjMUk43GSsZxkrCYZ60nGcIsDfQ00M9DBQNkDtdpTuV5A1P4f738BUEsDBBQAAAAIAC9WMlvBQU9k+gAAAFgCAAATABwAW0NvbnRlbnRfVHlwZXNdLnhtbCCiGAAooBQAAAAAAAAAAAAAAAAAAAAAAAAAAACtkj1OxDAQha9iuUWxsxQIoSRbAC1QcAHLmSTW+k+eyZI9GwVH4gp4HZQCISGkrUb2vPe+Gcuf7x/NfnGWHSGhCb7lO1FzBl6H3vix5TMN1S3fd83rKQKyLPXY8oko3kmJegKnUIQIPneGkJyifEyjjEof1Ajyuq5vpA6ewFNF5wzeNQ8wqNkSe1zy9YrNds7uV90Z1XIVozVaUW7Lo+9/QKowDEZDH/TsskVgTKB6nADIWVGqcMr4qxIsf2UmsPg/6PdWIjuLBicTcUM850dMpgf2ohI9KZfz5GLlW0iHMhDKUnbisstu+X8NgnSygBemr6EbWpZ/0n0BUEsBAi0AFAAAAAgAL1YyW1THejLHAAAAJwEAAA8AAAAAAAAAAAAAAAAAAAAAAHhsL3dvcmtib29rLnhtbFBLAQItAAoAAAAAAC9WMltDIIeIKAEAACgBAAALAAAAAAAAAAAAAAAAABABAABfcmVscy8ucmVsc1BLAQItABQAAAAIAC9WMlsv3c58hC4AAAoWAQAYAAAAAAAAAAAAAAAAAH0CAAB4bC93b3Jrc2hlZXRzL3NoZWV0MS54bWxQSwECLQAUAAAACAAvVjJb1YMSKdkAAAC9AQAAGgAAAAAAAAAAAAAAAABTMQAAeGwvX3JlbHMvd29ya2Jvb2sueG1sLnJlbHNQSwECLQAUAAAACAAvVjJb1sO1o5gBAADHBQAADQAAAAAAAAAAAAAAAACAMgAAeGwvc3R5bGVzLnhtbFBLAQItABQAAAAIAC9WMlvBQU9k+gAAAFgCAAATAAAAAAAAAAAAAAAAAF80AABbQ29udGVudF9UeXBlc10ueG1sUEsFBgAAAAAGAAYAgAEAAKY1AAAAAA==", ".xlsx", "Column4", "08/10/2025 17:04:25", "Column6", "Column7", "https://onelake.dfs.fabric.microsoft.com/d65a8c5a-8ab9-47a8-94f6-18a93be16d6e/0229fa72-7799-4106-ab94-61fd29fedf56/Files/Fichier_DTR-Perf_DCT-Perf_Net-ADDS%20par%20cluster/", "Export", "EVD Day", "EVD DoD", "EVD DoD Gap", ".", "EVD WTD", "EVD WoW", "EVD Gap WoW", "Daily POS", "EVD POS WoW", "RGA", "RGA DoD", "RGA DoD Gap", "RGA WoW", "RGA vs LW", "EVD MTD", "EVD MoM", "EVD Gap vs LM", "MoMo Bundle MoM", "MM Bundle Gap MoM", "RGA MoM", "RGA vs LM", "Export_1", "Sheet", "false"}),
  #"Choisir des colonnes" = Table.SelectColumns(#"Colonnes supprimées", {"01-09-2025 LOADING_DRIVERS.xlsx", "Zone - Zone", "Zone - Territory", "Zone - Cluster", "Lo Day Perf", "DTR Day", "DTC Day", "DTC Day Perf", "Lo MTD Perf", "DTR MTD", "DTR MoM", "DTR Gap vs LM", "DTC MTD", "DTC MTD Perf", "DTC MoM", "DTC Gap vs LM"}),
  #"Lignes filtrées" = Table.SelectRows(#"Choisir des colonnes", each ([#"Zone - Cluster"] <> null and [#"Zone - Cluster"] <> "Total" and [#"Zone - Cluster"] <> "Zone - Cluster")),
  #"Texte extrait avant le délimiteur" = Table.TransformColumns(#"Lignes filtrées", {{"01-09-2025 LOADING_DRIVERS.xlsx", each Text.BeforeDelimiter(_, " ", 0), type text}}),
  #"Type de colonne changé 1" = Table.TransformColumnTypes(#"Texte extrait avant le délimiteur", {{"01-09-2025 LOADING_DRIVERS.xlsx", type date}, {"Lo Day Perf", type number}, {"DTR Day", type number}, {"DTC Day", type number}, {"DTC Day Perf", type number}, {"Lo MTD Perf", type number}, {"DTR MTD", type number}, {"DTR MoM", type number}, {"DTR Gap vs LM", type number}, {"DTC MTD", type number}, {"DTC MTD Perf", type number}, {"DTC MoM", type number}, {"DTC Gap vs LM", type number}}),
  #"Colonnes renommées" = Table.RenameColumns(#"Type de colonne changé 1", {{"01-09-2025 LOADING_DRIVERS.xlsx", "Date"}, {"Zone - Zone", "Zone"}, {"Zone - Territory", "Territory"}, {"Zone - Cluster", "Cluster"}, {"Lo Day Perf", "DTR Day Perf"}}),
  #"Colonne personnalisée ajoutée 1" = Table.AddColumn(#"Colonnes renommées", "Target DTR day", each [DTR Day] / [DTR Day Perf]),
  #"Colonne personnalisée ajoutée 2" = Table.AddColumn(#"Colonne personnalisée ajoutée 1", "Target DTC day", each [DTC Day] / [DTC Day Perf]),
  #"Type de colonne changé 2" = Table.TransformColumnTypes(#"Colonne personnalisée ajoutée 2", {{"Target DTR day", type number}, {"Target DTC day", type number}}),
  #"Lignes triées" = Table.Sort(#"Type de colonne changé 2", {{"Cluster", Order.Ascending}})
in
  #"Lignes triées";
shared NavigationQuery = let
  Source = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false])
in
  Source;
shared DTR_DTC_cluster_nettoyé_DataDestination = let
  Pattern = Lakehouse.Contents([CreateNavigationProperties = false, EnableFolding = false]),
  Navigation_1 = Pattern{[workspaceId = "d65a8c5a-8ab9-47a8-94f6-18a93be16d6e"]}[Data],
  Navigation_2 = Navigation_1{[lakehouseId = "0229fa72-7799-4106-ab94-61fd29fedf56"]}[Data],
  TableNavigation = Navigation_2{[Id = "DTR_DTC_cluster_nettoyé", ItemKind = "Table"]}?[Data]?
in
  TableNavigation;
